name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/review-planner

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Declare image tag
      - name: Set date tag
        run: echo "PRD_TAG=prd-$(date +'%Y%m%d')" >> $GITHUB_ENV

      # Build image
      - name: Build Docker image
        run: docker build -t $DOCKER_REPO:$PRD_TAG .

      # Push image
      - name: Push Docker image
        run: docker push $DOCKER_REPO:$PRD_TAG

